# .github/workflows/badge-only.yml
name: GitHub Actions Badge Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  badge-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo success
        run: echo "🎉 GitHub Actions badge triggered by Naz!"
